refactor: replace Spinner of Shell with the DS one
Zextras/carbonio-auth-ui pull request #102
Opened 2024-11-13 16:51 UTC by rodleyorosa

Refs: CO-1652

Spinner of Shell will be removed:
https://zextras.atlassian.net/browse/SHELL-254
https://github.com/zextras/carbonio-shell-ui/pull/544

2024-11-13 16:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zextras/carbonio-auth-ui?pullRequest=102) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zextras/carbonio-auth-ui?pullRequest=102) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zextras/carbonio-auth-ui?pullRequest=102) it.</sub>

2024-11-15 09:34 UTC, gnekoz submitted a review, later dismissed

2024-12-13 17:20 UTC, gnekoz requested changes

2024-12-13 17:20 UTC, gnekoz commented on src/app.jsx
>  		<LazyAuth {...props} />
There are few Prettier errors that cause the build to fail

2024-12-17 09:00 UTC, gnekoz approved these changes

2024-12-18 15:30 UTC, frisonisland approved these changes

2024-12-19 08:27 UTC, merged